name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_achievements: yes
          plugin_reactions: yes
          plugin_reactions_details: count
          plugin_languages: yes
          plugin_gists: yes
          plugin_languages_details: bytes-size, percentage, lines
